-- Einsatzberichte (Phase A) – angelehnt an FW-Hub incident_reports

CREATE TABLE incident_types (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    type_key    VARCHAR(64)  NOT NULL,
    label       VARCHAR(255) NOT NULL,
    category    VARCHAR(64)  NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_incident_types_key UNIQUE (type_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_incident_types_category ON incident_types (category);
CREATE INDEX idx_incident_types_active ON incident_types (active);

INSERT INTO incident_types (type_key, label, category, sort_order) VALUES
    ('B1',          'B1 – Brand klein',             'Brand',     10),
    ('B2',          'B2 – Brand mittel',            'Brand',     20),
    ('B2_GEBAEUDE', 'B2 – Brand Gebäude',           'Brand',     25),
    ('B3',          'B3 – Brand groß',              'Brand',     30),
    ('B3_GEBAEUDE', 'B3 – Brand Gebäude (groß)',    'Brand',     35),
    ('BMA',         'BMA-Auslösung',                'Brand',     40),
    ('TH1',         'TH1 – Hilfeleistung klein',    'THL',       10),
    ('TH1_TUER',    'TH1 – Türnotöffnung',          'THL',       15),
    ('TH2',         'TH2 – Hilfeleistung mittel',   'THL',       20),
    ('TH2_VU',      'TH2 – Verkehrsunfall',         'THL',       25),
    ('TH2_KLEMM',   'TH2 – Person eingeklemmt',     'THL',       30),
    ('TH3',         'TH3 – Hilfeleistung groß',     'THL',       35),
    ('HPWASSER',    'Person im Wasser',             'THL',       40),
    ('HPSPRUNG',    'Person droht zu springen',     'THL',       45),
    ('HSGEFGUT',    'Gefahrguteinsatz',             'Gefahrgut', 10),
    ('FEHLALARM',   'Fehlalarm',                    'Fehlalarm', 10),
    ('RWM',         'Rauchwarnmelder (kein Brand)', 'Fehlalarm', 20),
    ('UNW',         'Unwetter',                     'Sonstiges', 10),
    ('TIER',        'Tier in Notlage',              'Sonstiges', 20),
    ('SONSTIGES',   'Sonstiges',                    'Sonstiges', 99);

CREATE TABLE incident_reports (
    id                          BIGINT AUTO_INCREMENT PRIMARY KEY,
    unit_id                     BIGINT       NOT NULL,
    incident_number             VARCHAR(32),
    incident_date               DATE         NOT NULL,
    alarm_time                  TIME         NULL,
    departure_time              TIME         NULL,
    arrival_time                TIME         NULL,
    end_time                    TIME         NULL,
    incident_type_key           VARCHAR(64)  NOT NULL DEFAULT 'SONSTIGES',
    incident_type_label         VARCHAR(255) NOT NULL DEFAULT 'Sonstiges',
    location                    VARCHAR(300) NOT NULL,
    postal_code                 VARCHAR(10)  NULL,
    district                    VARCHAR(128) NULL,
    street                      VARCHAR(255) NULL,
    house_number                VARCHAR(20)  NULL,
    extinguished_before_arrival BOOLEAN      NOT NULL DEFAULT FALSE,
    malicious_alarm             BOOLEAN      NOT NULL DEFAULT FALSE,
    false_alarm                 BOOLEAN      NOT NULL DEFAULT FALSE,
    supraregional               BOOLEAN      NOT NULL DEFAULT FALSE,
    bf_involved                 BOOLEAN      NOT NULL DEFAULT FALSE,
    violence_against_crew       BOOLEAN      NOT NULL DEFAULT FALSE,
    violence_count              INT          NOT NULL DEFAULT 0,
    incident_commander          VARCHAR(255) NULL,
    reporter_name               VARCHAR(255) NULL,
    reporter_phone              VARCHAR(64)  NULL,
    strength_leadership         INT          NOT NULL DEFAULT 0,
    strength_sub                INT          NOT NULL DEFAULT 0,
    strength_crew               INT          NOT NULL DEFAULT 0,
    fire_object                 VARCHAR(512) NULL,
    situation                   TEXT         NULL,
    measures                    TEXT         NULL,
    notes                       TEXT         NULL,
    thl_type                    VARCHAR(255) NULL,
    weather_influence           VARCHAR(255) NULL,
    handover_to                 VARCHAR(255) NULL,
    handover_notes              TEXT         NULL,
    police_case_number          VARCHAR(128) NULL,
    police_station              VARCHAR(255) NULL,
    police_officer              VARCHAR(255) NULL,
    persons_rescued             INT          NOT NULL DEFAULT 0,
    persons_evacuated           INT          NOT NULL DEFAULT 0,
    persons_injured             INT          NOT NULL DEFAULT 0,
    persons_injured_own         INT          NOT NULL DEFAULT 0,
    persons_recovered           INT          NOT NULL DEFAULT 0,
    persons_dead                INT          NOT NULL DEFAULT 0,
    persons_dead_own            INT          NOT NULL DEFAULT 0,
    animals_rescued             INT          NOT NULL DEFAULT 0,
    animals_injured             INT          NOT NULL DEFAULT 0,
    animals_recovered           INT          NOT NULL DEFAULT 0,
    animals_dead                INT          NOT NULL DEFAULT 0,
    vehicle_damage              TEXT         NULL,
    equipment_damage            TEXT         NULL,
    resources_json              TEXT         NOT NULL,
    status                      VARCHAR(16)  NOT NULL DEFAULT 'ENTWURF',
    created_by_user_id          BIGINT       NULL,
    created_by_name             VARCHAR(255) NULL,
    released_by_user_id         BIGINT       NULL,
    released_at                 TIMESTAMP    NULL,
    test_data                   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incident_report_unit FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE CASCADE,
    CONSTRAINT fk_incident_report_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_incident_report_released_by FOREIGN KEY (released_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT uk_incident_report_number_unit UNIQUE (unit_id, incident_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_incident_reports_unit_date ON incident_reports (unit_id, incident_date DESC);
CREATE INDEX idx_incident_reports_unit_status ON incident_reports (unit_id, status);
