-- Manuell angelegte Einsätze (ohne Testmodus), sichtbar auf Startseite + Einsatz-App

CREATE TABLE manual_alarms (
    id                      BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    unit_id                 BIGINT       NOT NULL,
    alarm_id                BIGINT       NOT NULL,
    alarm_number            VARCHAR(64)  NULL,
    incident_category       VARCHAR(128) NULL,
    title                   VARCHAR(512) NOT NULL,
    alarm_text              TEXT         NULL,
    meldebild_zusatz        VARCHAR(512) NULL,
    address                 VARCHAR(512) NULL,
    street                  VARCHAR(255) NULL,
    house_number            VARCHAR(64)  NULL,
    postal_code             VARCHAR(16)  NULL,
    city                    VARCHAR(128) NULL,
    district                VARCHAR(128) NULL,
    object_name             VARCHAR(255) NULL,
    reporter_name           VARCHAR(255) NULL,
    reporter_phone          VARCHAR(64)  NULL,
    callback_phone          VARCHAR(64)  NULL,
    meldeweg                VARCHAR(128) NULL,
    beteiligte_einsatzmittel VARCHAR(512) NULL,
    route_info              TEXT         NULL,
    leitstelle_name         VARCHAR(255) NULL,
    leitstelle_address      VARCHAR(512) NULL,
    leitstelle_phone        VARCHAR(64)  NULL,
    leitstelle_email        VARCHAR(255) NULL,
    date_epoch_seconds      BIGINT       NOT NULL,
    ts_create_seconds       BIGINT       NOT NULL,
    closed                  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at               TIMESTAMP    NULL,
    created_by_user_id      BIGINT       NULL,
    CONSTRAINT fk_manual_alarms_unit FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE CASCADE,
    CONSTRAINT fk_manual_alarms_user FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    UNIQUE KEY uk_manual_alarms_unit_alarm (unit_id, alarm_id),
    INDEX idx_manual_alarms_unit_open (unit_id, closed, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
