package de.feuerwehr.manager.berichte;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

public record EinsatzberichtFormData(
        String incidentNumber,
        LocalDate incidentDate,
        LocalTime alarmTime,
        LocalTime departureTime,
        LocalTime arrivalTime,
        LocalTime endTime,
        String stichwort,
        String location,
        String postalCode,
        String district,
        String street,
        String houseNumber,
        String objekt,
        String eigentuemer,
        boolean extinguishedBeforeArrival,
        boolean maliciousAlarm,
        boolean falseAlarm,
        boolean supraregional,
        boolean bfInvolved,
        boolean violenceAgainstCrew,
        int violenceCount,
        Long commanderPersonId,
        String incidentCommander,
        String reporterName,
        String reporterPhone,
        List<Long> personnelPersonIds,
        List<Long> vehicleIds,
        String einsatzkurzbericht,
        int personsRescued,
        int personsEvacuated,
        int personsInjured,
        int personsInjuredOwn,
        int personsRecovered,
        int personsDead,
        int personsDeadOwn,
        int animalsRescued,
        int animalsInjured,
        int animalsRecovered,
        int animalsDead,
        String vehicleDamage,
        String equipmentDamage) {}
